[build]
  publish = "."

[form]
  [form.settings]
    name = "contact"
    notification = true
    honeypot = true
    notification_email = "contact@tomorebeyond.co"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"